language: node_js
node_js:
  - 4
  - 12

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libxml2-dev

before_script:
  - 'npm install'
  - 'node audio-service.js &'

script:
  - npm test
