#!/bin/bash

cd $FIELDDB_HOME/AudioWebService
#bash switch_to_producti.sh

forever \
start \
-al $FIELDDB_HOME/logs/fielddbaudio.log \
-ao $FIELDDB_HOME/logs/fielddbaudioout.log \
-ae $FIELDDB_HOME/logs/fielddbaudioerr.log \
service.js


