#!/bin/bash

cd $FIELDDB_HOME/AudioWebService
export NODE_ENV="production"

forever \
start \
-al $FIELDDB_HOME/logs/fielddbaudio.log \
-ao $FIELDDB_HOME/logs/fielddbaudioout.log \
-ae $FIELDDB_HOME/logs/fielddbaudioerr.log \
audio-service.js

echo "Running tests to be sure all is well..."
npm test
