# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [  main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: sudo apt-get update
    - run: sudo apt-get -y install praat
    - run: sudo apt-get -y install ffmpeg
    - run: which avconv || echo "avconv didnt install"
    # - run: sudo apt-get -y install libav-tools
    # - run: which avconv || echo "avconv didnt install"
    - run: which ffmpeg || echo "ffmpeg didnt install"
    # - run: avconv -v || echo "avconv didnt install"
    - run: ffmpeg -version || echo "ffmpeg didnt install"
    - run: npm ci
    - run: npm test || npm test
    - run: NODE_ENV=local npm start &
